export const Trasaction_DUMMY_DATA = [
  {
    id: '1',
    category: 'Invest Transaction',
    product: {
      title: 'Online Payments',
      subtitle: 'Amplio Wealth Theme 1',
      icon: 'solar:card-recive-bold-duotone',
      minimumAmount: 25000,
      minimumAmountFormatted: '₹25,000.00',
      lockIn: '7 Days',
      interestRate: '10%',
      interestRateLabel: 'upto 10% p.a.',
      payoutCycle: 'Weekly Repayment Cycle',
      payoutLabel: 'Interest payout',
    },
  },
  {
    id: '2',
    category: 'Invest Transaction',
    product: {
      title: 'Retail Settlements',
      subtitle: 'Amplio Wealth Theme 2',
      icon: 'solar:wallet-money-bold-duotone',
      minimumAmount: 50000,
      minimumAmountFormatted: '₹50,000.00',
      lockIn: '14 Days',
      interestRate: '11%',
      interestRateLabel: 'upto 11% p.a.',
      payoutCycle: 'Weekly Repayment Cycle',
      payoutLabel: 'Interest payout',
    },
  },
  {
    id: '3',
    category: 'Invest Transaction',
    product: {
      title: 'Invoice Financing',
      subtitle: 'Amplio Wealth Theme 3',
      icon: 'solar:bill-list-bold-duotone',
      minimumAmount: 75000,
      minimumAmountFormatted: '₹75,000.00',
      lockIn: '21 Days',
      interestRate: '12%',
      interestRateLabel: 'upto 12% p.a.',
      payoutCycle: 'Bi-weekly Repayment Cycle',
      payoutLabel: 'Interest payout',
    },
  },
  {
    id: '4',
    category: 'Invest Transaction',
    product: {
      title: 'Pharma Distribution',
      subtitle: 'Amplio Wealth Theme 4',
      icon: 'solar:box-bold-duotone',
      minimumAmount: 100000,
      minimumAmountFormatted: '₹1,00,000.00',
      lockIn: '30 Days',
      interestRate: '12.5%',
      interestRateLabel: 'upto 12.5% p.a.',
      payoutCycle: 'Monthly Repayment Cycle',
      payoutLabel: 'Interest payout',
    },
  },
  {
    id: '5',
    category: 'Invest Transaction',
    product: {
      title: 'E-commerce Payouts',
      subtitle: 'Amplio Wealth Theme 5',
      icon: 'solar:shop-bold-duotone',
      minimumAmount: 125000,
      minimumAmountFormatted: '₹1,25,000.00',
      lockIn: '45 Days',
      interestRate: '13%',
      interestRateLabel: 'upto 13% p.a.',
      payoutCycle: 'Monthly Repayment Cycle',
      payoutLabel: 'Interest payout',
    },
  },
  {
    id: '6',
    category: 'Invest Transaction',
    product: {
      title: 'Logistics Advances',
      subtitle: 'Amplio Wealth Theme 6',
      icon: 'solar:bus-bold-duotone',
      minimumAmount: 150000,
      minimumAmountFormatted: '₹1,50,000.00',
      lockIn: '60 Days',
      interestRate: '13.5%',
      interestRateLabel: 'upto 13.5% p.a.',
      payoutCycle: 'Monthly Repayment Cycle',
      payoutLabel: 'Interest payout',
    },
  },
];
